
path: /home/lucas/Documents/EdraTrainee
train: train/train/images # train images (relative to 'path')
val: train/train/images  # val images (relative to 'path')

# Classes
names:
  0: circulo-com-sinal-positivo